### ISSUE TITLE
Do not mark @types/X as unused if X is used

### ISSUE THREAD

**Issue by joeflateau** [trumbitta/nx-trumbitta#59]
Title says it all, `@types/express` should not be flagged as unused when `express` is used

**Comment by trumbitta** [comment]
Hey Joe 🎸 🎶 

Is this about `nx-plugin-unused-deps`? 🤔 
Good catch! I would expect all of the `@types` packages to always end up flagged as unused because the dependency graph can't find them directly imported anywhere. 💡 

It should be a fun a little edge case to work on for a contributor. Maybe you are interested? 😺 

I'll add the proper label for now. I'm not sure when I'll be able to work on it myself.
